apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://127.0.0.1:57000
    namespace: default
  project: default
  source:
    path: charts/argo-cd
    repoURL: https://github.com/parce-pi/argotest.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
