apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  project: default
  source:
    chart: elasticsearch
    helm:
      values: |
        cluster: https://kubernetes.default.svc
        project: default
    repoURL: https://helm.elastic.co
    targetRevision: 7.10.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true